[2024-02-25T14:13:10.587+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: demo.airflow scheduled__2022-01-14T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
