[2024-02-26T18:30:07.827+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cronTrigger.select_priority manual__2024-02-26T18:30:05.446680+00:00 [queued]>
[2024-02-26T18:30:07.842+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cronTrigger.select_priority manual__2024-02-26T18:30:05.446680+00:00 [queued]>
[2024-02-26T18:30:07.843+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T18:30:07.866+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): select_priority> on 2024-02-26 18:30:05.446680+00:00
[2024-02-26T18:30:07.874+0000] {standard_task_runner.py:60} INFO - Started process 92 to run task
[2024-02-26T18:30:07.879+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cronTrigger', 'select_priority', 'manual__2024-02-26T18:30:05.446680+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/cronTrigger.py', '--cfg-path', '/tmp/tmp0b1sql9y']
[2024-02-26T18:30:07.883+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask select_priority
[2024-02-26T18:30:07.953+0000] {task_command.py:423} INFO - Running <TaskInstance: cronTrigger.select_priority manual__2024-02-26T18:30:05.446680+00:00 [running]> on host 81dc7f67df81
[2024-02-26T18:30:08.078+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cronTrigger' AIRFLOW_CTX_TASK_ID='select_priority' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T18:30:05.446680+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T18:30:05.446680+00:00'
[2024-02-26T18:30:08.082+0000] {sql.py:276} INFO - Executing: select * from priorities
[2024-02-26T18:30:08.098+0000] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2024-02-26T18:30:08.114+0000] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2024-02-26T18:30:08.117+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2024-02-26T18:30:08.129+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cronTrigger, task_id=select_priority, execution_date=20240226T183005, start_date=20240226T183007, end_date=20240226T183008
[2024-02-26T18:30:08.144+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task select_priority (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 92)
[2024-02-26T18:30:08.172+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T18:30:08.224+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
